version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1469191292
layout:
  /header/:
    -
      - spacer-2597
  /navigation/:
    -
      - 'logo-1633 21'
      - 'menu-4541 79'
  /main/:
    -
      - system-content-1635
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6432 12'
      - 'date-6732 38'
      - 'spacer-4331 25'
      - 'branding-9556 25'
  offcanvas:
    -
      - mobile-menu-7727
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  logo-1633:
    attributes:
      image: 'gantry-media://logo.png'
  position-footer:
    attributes:
      key: footer
  copyright-6432:
    attributes:
      enabled: 0
  branding-9556:
    attributes:
      content: "©Delicious.  Developer with  <i class=\"fa fa-heart-o bounceIn animated infinite \" style=\"color: #FF0000;\"></i> By  <a href=\"http://web-komp.eu\" title=\"WebKomp\" class=\"g-powered-by\">WebKomp</a>\n\n\n"
