version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1462124650
layout:
  /header/:
    -
      - 'position-position-9165 33.3'
      - 'position-position-3848 33.3'
      - 'position-position-6042 33.3'
  /navigation/:
    -
      - 'logo-8433 20'
      - 'menu-2758 80'
    -
      - 'position-position-3226 33.3'
      - 'position-position-6585 33.3'
      - 'position-position-6673 33.3'
  /slideshow/:
    -
      - position-position-4067
  /top/:
    -
      - 'position-position-7642 33.3'
      - 'position-position-5544 33.3'
      - 'position-position-5776 33.3'
  /showcase/:
    -
      - 'position-position-8121 33.3'
      - 'position-position-5404 33.3'
      - 'position-position-2509 33.3'
  /utility/:
    -
      - 'position-position-8460 33.3'
      - 'position-position-5807 33.3'
      - 'position-position-8744 33.3'
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - position-position-9790
      -
        'mainbar 60':
          -
            - 'position-position-9178 33.3'
            - 'position-position-8966 33.3'
            - 'position-position-9290 33.3'
          -
            - system-content-9532
      -
        'aside 20':
          -
            - position-position-6029
  /extension/:
    -
      - 'position-position-9539 33.3'
      - 'position-position-5616 33.3'
      - 'position-position-1334 33.3'
  /bottom/:
    -
      - 'position-position-5629 33.3'
      - 'position-position-6558 33.3'
      - 'position-position-2521 33.3'
  /footer/:
    -
      - 'position-position-4173 25'
      - 'position-position-7002 25'
      - 'position-position-5898 25'
      - 'position-footer 25'
  /copyright/:
    -
      - 'copyright-1069 33.3'
      - 'branding-7884 33.3'
      - 'totop-5132 33.3'
  offcanvas:
    -
      - mobile-menu-7283
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  slideshow:
    type: section
    attributes:
      boxed: '2'
      class: ''
  top:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-main:
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
content:
  position-position-9165:
    title: Header-A
    attributes:
      key: header-a
  position-position-3848:
    title: Header-B
    attributes:
      key: header-b
  position-position-6042:
    title: Header-C
    attributes:
      key: header-c
  logo-8433:
    title: 'Logo / Image'
  position-position-3226:
    title: Navigation-A
    attributes:
      key: navigation-a
  position-position-6585:
    title: Navigation-B
    attributes:
      key: navigation-b
  position-position-6673:
    title: Navigation-C
    attributes:
      key: navigation-c
  position-position-4067:
    title: Slideshow
    attributes:
      key: slideshow
  position-position-7642:
    title: 'Top A'
    attributes:
      key: top-a
  position-position-5544:
    title: 'Top B'
    attributes:
      key: top-b
  position-position-5776:
    title: 'Top C'
    attributes:
      key: top-c
  position-position-8121:
    title: Showcase-A
    attributes:
      key: showcase-a
  position-position-5404:
    title: Showcase-B
    attributes:
      key: showcase-b
  position-position-2509:
    title: Showcase-C
    attributes:
      key: showcase-c
  position-position-8460:
    title: Utility-A
    attributes:
      key: utility-a
  position-position-5807:
    title: Utility-B
    attributes:
      key: utility-b
  position-position-8744:
    title: Utility-C
    attributes:
      key: utility-c
  position-position-9790:
    title: Sidebar
    attributes:
      key: sidebar
  position-position-9178:
    title: Mainbar-A
    attributes:
      key: mainbar-a
  position-position-8966:
    title: Mainbar-B
    attributes:
      key: mainbar-b
  position-position-9290:
    title: Mainbar-C
    attributes:
      key: mainbar-c
  position-position-6029:
    title: Aside
    attributes:
      key: aside
  position-position-9539:
    title: Extension-A
    attributes:
      key: extension-a
  position-position-5616:
    title: Extension-B
    attributes:
      key: extension-b
  position-position-1334:
    title: Extension-C
    attributes:
      key: extension-c
  position-position-5629:
    title: Bottom-A
    attributes:
      key: bottom-a
  position-position-6558:
    title: Bottom-B
    attributes:
      key: bottom-b
  position-position-2521:
    title: Bottom-C
    attributes:
      key: bottom-c
  position-position-4173:
    title: Footer-A
    attributes:
      key: footer-a
  position-position-7002:
    title: Footer-B
    attributes:
      key: footer-b
  position-position-5898:
    title: Footer-C
    attributes:
      key: footer-c
  position-footer:
    title: Footer-D
    attributes:
      key: footer-d
  copyright-1069:
    attributes:
      date:
        end: ''
      owner: www.web-komp.eu
  branding-7884:
    attributes:
      enabled: 0
      content: 'Powered by <a href="http://www.gantry.org/" title="Gantry Framework" class="g-powered-by">Gantry Framework</a>'
  totop-5132:
    title: 'To Top'
    attributes:
      icon: 'fa fa-angle-double-up fa-fw fa-lg'
      content: ''
