name: _offline
timestamp: 1562649532
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1469191292
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-6113: Logo
  spacer:
    spacer-6539: Spacer
    spacer-5663: Spacer
  messages:
    system-messages-4833: 'System Messages'
  content:
    system-content-3011: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-6361: Copyright
  branding:
    branding-8689: Branding
inherit: {  }
