name: 11
timestamp: 1562653759
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1562653759
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  messages:
    system-messages-2737: 'System Messages'
  logo:
    logo-3213: 'Logo / Image'
    logo-8216: 'Logo / Image'
  menu:
    menu-8946: Menu
  social:
    social-4732: Social
  copyright:
    copyright-8137: Copyright
  horizontalmenu:
    horizontalmenu-3404: 'Horizontal Menu'
  totop:
    totop-7283: 'To Top'
  mobile-menu:
    mobile-menu-1691: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-2737: system-messages-7899
    logo-3213: logo-2216
    menu-8946: menu-4318
    social-4732: social-5141
    logo-8216: logo-8610
    copyright-8137: copyright-6915
    horizontalmenu-3404: horizontalmenu-8926
    totop-7283: totop-6132
    mobile-menu-1691: mobile-menu-3944
