name: _body_only
timestamp: 1562649532
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1469191292
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-9747: 'System Messages'
  content:
    system-content-9817: 'Page Content'
inherit: {  }
