name: _body_only
timestamp: 1562653777
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1562653777
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-7207: 'System Messages'
  content:
    system-content-5360: 'Page Content'
inherit: {  }
