version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1562653777
layout:
  /main/:
    -
      - system-messages-7207
    -
      - system-content-5360
structure:
  main:
    attributes:
      boxed: ''
